language: r
cache: packages
r:
  - oldrel
  - release
  - devel
os:
  - linux
jobs:
  exclude:
  - r: devel
    os: osx
before_script:
  - sudo apt-get install libcgal-dev libglu1-mesa-dev
after_success:
    - Rscript -e 'covr::codecov()'

