env:
  - NOT_CRAN=true
language: r
cache: packages
r:
  - oldrel
  - release
  - devel
os:
  - linux
  - osx
jobs:
  exclude:
  - r: devel
    os: osx
addons:
  apt:
    packages:
    - libcgal-dev
    - libglu1-mesa-dev
after_success:
    - Rscript -e 'covr::codecov()'

